name: Purge jsDelivr cache

# Trigger on every push to any branch (or restrict to main:)
on:
  push:
    branches:
      - main

jobs:
   purge:
      runs-on: ubuntu-latest
      steps:
         - name: Purge jsDelivr edge cache
           uses: gacts/purge-jsdelivr-cache@v1
           with:
             url: |
               https://cdn.jsdelivr.net/gh/goodguyswebagency/Zip-Up@latest/global.css
               https://cdn.jsdelivr.net/gh/goodguyswebagency/Zip-Up@latest/global.js